version: '3'
services:
  api:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "5005:5005"
    volumes:
      - .:/usr/src/
    extra_hosts:
    - "host.docker.internal:host-gateway"

